# Generated by Django 3.0.5 on 2020-06-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=50, verbose_name='中文名称')),
                ('project_ename', models.CharField(default='', max_length=200, verbose_name='英文名称')),
                ('sys_version', models.CharField(blank=True, default='', max_length=100, verbose_name='运行版本')),
                ('namespace', models.CharField(default='', max_length=100, verbose_name='K8s命名空间')),
                ('sys_id', models.CharField(max_length=100, verbose_name='应用实例')),
                ('notes', models.TextField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.CharField(blank=True, default='', max_length=50, verbose_name='创建者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('editor', models.CharField(blank=True, default='', max_length=50, verbose_name='更新人')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='normal_app.Project')),
            ],
            options={
                'verbose_name': '项目服务多对多',
                'verbose_name_plural': '项目服务多对多',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=32, unique=True, verbose_name='类型名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '项目类型',
                'verbose_name_plural': '项目类型',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=150, verbose_name='服务名称')),
                ('service_cname', models.CharField(default='中文名称', max_length=150, verbose_name='服务中文名称')),
                ('service_port', models.IntegerField(default=8000, verbose_name='服务端口')),
                ('protocol_type', models.CharField(max_length=20, verbose_name='协议类型')),
                ('config_version', models.CharField(default='202006301537', max_length=100, verbose_name='配置版本号')),
                ('service_type', models.IntegerField(choices=[(1, 'mysql'), (2, 'mongodb'), (3, 'redis'), (4, 'others')], default=4, verbose_name='服务类型')),
                ('notes', models.TextField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('projects', models.ManyToManyField(through='normal_app.ProjectService', to='normal_app.Project')),
            ],
            options={
                'verbose_name': '服务信息',
                'verbose_name_plural': '服务信息',
            },
        ),
        migrations.CreateModel(
            name='Vmachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_ID', models.CharField(default='', max_length=100, verbose_name='虚机ID')),
                ('vm_ip', models.CharField(default='0.0.0.0', max_length=20, verbose_name='虚机IP')),
                ('vm_vcore', models.IntegerField(default=1, verbose_name='虚机核数')),
                ('vm_ram', models.IntegerField(default=4, verbose_name='虚机内存/G')),
                ('vm_size', models.IntegerField(default=1, verbose_name='系统盘大小/G')),
                ('vm_disc', models.CharField(default='', max_length=200, verbose_name='虚机描述')),
                ('vm_available', models.IntegerField(choices=[(1, '使用中'), (0, '空闲中')], default=0, verbose_name='使用情况')),
                ('vm_type', models.IntegerField(choices=[(1, 'controller'), (0, 'working')], default=0, verbose_name='虚机类型')),
                ('node_name', models.CharField(default='', max_length=200, verbose_name='工作节点')),
                ('vm_grafana_label', models.CharField(default='', max_length=200, verbose_name='G标签')),
                ('vm_prometheus_label', models.CharField(default='', max_length=200, verbose_name='P标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '虚机信息',
                'verbose_name_plural': '虚机信息',
            },
        ),
        migrations.CreateModel(
            name='Vmdisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_name', models.CharField(max_length=50, verbose_name='数据盘的名称')),
                ('disk_size', models.IntegerField(verbose_name='数据盘的大小')),
                ('disk_disc', models.CharField(default='', max_length=200, verbose_name='数据盘的用途说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='normal_app.Vmachine', verbose_name='绑定的虚机')),
            ],
            options={
                'verbose_name': '数据盘信息',
                'verbose_name_plural': '数据盘信息',
            },
        ),
        migrations.CreateModel(
            name='ServiceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.IntegerField(choices=[(1, 'Genenral'), (2, 'ENV_VERSION')], default=1, verbose_name='配置类型')),
                ('config_name', models.CharField(blank=True, default='', max_length=100, verbose_name='配置名称')),
                ('config_value', models.CharField(blank=True, default='', max_length=200, verbose_name='配置值')),
                ('config_disc', models.CharField(blank=True, default='', max_length=200, verbose_name='配置说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('service_name', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='normal_app.Service', verbose_name='服务名称')),
            ],
            options={
                'verbose_name': '服务配置',
                'verbose_name_plural': '服务配置',
            },
        ),
        migrations.AddField(
            model_name='projectservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='normal_app.Service'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='normal_app.ProjectType', verbose_name='项目类型'),
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(through='normal_app.ProjectService', to='normal_app.Service'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.IntegerField(choices=[(1, 'Genenral'), (2, 'Standalone'), (3, 'ShardCluster'), (4, 'ReplicaSet')], default=1, verbose_name='账号类型')),
                ('account_name', models.CharField(default='', max_length=100, verbose_name='帐号名称')),
                ('account_password', models.CharField(default='', max_length=100, verbose_name='账号密码')),
                ('account_level', models.IntegerField(choices=[(1, '管理员用账号'), (2, '使用者账号')], default=1, verbose_name='账号等级')),
                ('db_name', models.CharField(default='', max_length=100, verbose_name='数据库名称')),
                ('auth_db', models.CharField(default='', max_length=100, verbose_name='MongoAdmin_DB')),
                ('notes', models.TextField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, help_text='逻辑删除', verbose_name='逻辑删除')),
                ('service_name', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='normal_app.Service', verbose_name='服务名称')),
            ],
            options={
                'verbose_name': '账密配置',
                'verbose_name_plural': '账密配置',
            },
        ),
    ]
